apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    generation: 1
    name: python-simple-http-server
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: python-simple-http-server
    name: python-simple-http-server
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: python-simple-http-server:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/jewzaam/python-simple-http-server.git
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        env:
        - name: GIT_SSL_NO_VERIFY
          value: "true"
        from:
          kind: ImageStreamTag
          name: python:2.7
          namespace: openshift
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - type: Generic
      generic:
        secret: "jewzaam-simple"
kind: List
metadata: {}

