apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftCreate
  labels:
    app: simple-python-http-server
  name: simple-python-http-server
  namespace: test-project
  selfLink: /api/v1/namespaces/test-project/services/simple-python-http-server
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-python-http-server
    deploymentconfig: simple-python-http-server
  sessionAffinity: None
  type: ClusterIP
